FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN apt-get install -y nodejs

WORKDIR /opt/webserver
COPY . /opt/webserver

RUN npm install aws-sdk

EXPOSE 8003:8003
CMD ["./webserver", "test_config"]
